# API
server.port=8080
server.servlet.context-path=/api/v0

# BBDD
spring.datasource.url=jdbc:h2:mem:compra_tu_auto_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# HIBERNATE / JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# JACKSON
spring.jackson.property-naming-strategy=SNAKE_CASE